trigger:
- main  # This triggers the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version (e.g., '3.11')
    addToPath: true

- script: |
    python -m venv .venv  # Create a virtual environment
    source .venv/bin/activate  # Activate the virtual environment
    pip install -r requirements.txt  # Install dependencies from requirements.txt
  displayName: 'Set up Python environment and install dependencies'

- script: |
    zip -r ServerlessAPI.zip *  # Package the function app into a zip file
  displayName: 'Package Python Function App'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/ServerlessAPI.zip'
    artifactName: 'drop'
  displayName: 'Publish build artifacts'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'azureSPconnection'  # Your Azure service connection name
    appType: 'functionAppLinux'  # Use 'functionAppLinux' for Python functions
    appName: 'appfunctn'  # Your Function App name
    package: '$(System.DefaultWorkingDirectory)/ServerlessAPI.zip'
  displayName: 'Deploy to Azure Function App'